syntax = "proto3";

import "google/protobuf/empty.proto";

option go_package = "github.com/Daylily-kor/daylily-docker-client/proto/dockerpb";
option java_multiple_files = true;
option java_package = "com.daylily.proto";
option java_outer_classname = "DockerPb";

service DockerService {
  rpc Version(google.protobuf.Empty) returns (VersionResponse);
  rpc Build(BuildRequest) returns (BuildResponse);
  rpc Run(RunRequest) returns (RunResponse);
}

message VersionResponse {
  string version = 1;
  string api_version = 2;
  string platform = 3;
  string os = 4;
  string arch = 5;
  string kernel_version = 6;
}

message BuildRequest {
  string owner = 1;
  string repository = 2;
  string ref = 3;
}

message BuildResponse {
  string image_name = 1;
}

message RunRequest {
  string image_name = 1;
}

message RunResponse {
  string container_id = 1;
  string status = 2;
}