// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/dockerpb/dockerpb.proto

package dockerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	KernelVersion string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dockerpb_dockerpb_proto_rawDescGZIP(), []int{0}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *VersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VersionResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *VersionResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *VersionResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_dockerpb_dockerpb_proto_rawDescGZIP(), []int{1}
}

func (x *BuildRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BuildRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *BuildRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_proto_dockerpb_dockerpb_proto_rawDescGZIP(), []int{2}
}

func (x *BuildResponse) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_dockerpb_dockerpb_proto_rawDescGZIP(), []int{3}
}

func (x *RunRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dockerpb_dockerpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_dockerpb_dockerpb_proto_rawDescGZIP(), []int{4}
}

func (x *RunResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_dockerpb_dockerpb_proto protoreflect.FileDescriptor

const file_proto_dockerpb_dockerpb_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/dockerpb/dockerpb.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb3\x01\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\"V\n" +
	"\fBuildRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\".\n" +
	"\rBuildResponse\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\"+\n" +
	"\n" +
	"RunRequest\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\"H\n" +
	"\vRunResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x8e\x01\n" +
	"\rDockerService\x123\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\x10.VersionResponse\x12&\n" +
	"\x05Build\x12\r.BuildRequest\x1a\x0e.BuildResponse\x12 \n" +
	"\x03Run\x12\v.RunRequest\x1a\f.RunResponseB\\\n" +
	"\x11com.daylily.protoB\bDockerPbP\x01Z;github.com/Daylily-kor/daylily-docker-client/proto/dockerpbb\x06proto3"

var (
	file_proto_dockerpb_dockerpb_proto_rawDescOnce sync.Once
	file_proto_dockerpb_dockerpb_proto_rawDescData []byte
)

func file_proto_dockerpb_dockerpb_proto_rawDescGZIP() []byte {
	file_proto_dockerpb_dockerpb_proto_rawDescOnce.Do(func() {
		file_proto_dockerpb_dockerpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dockerpb_dockerpb_proto_rawDesc), len(file_proto_dockerpb_dockerpb_proto_rawDesc)))
	})
	return file_proto_dockerpb_dockerpb_proto_rawDescData
}

var file_proto_dockerpb_dockerpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dockerpb_dockerpb_proto_goTypes = []any{
	(*VersionResponse)(nil), // 0: VersionResponse
	(*BuildRequest)(nil),    // 1: BuildRequest
	(*BuildResponse)(nil),   // 2: BuildResponse
	(*RunRequest)(nil),      // 3: RunRequest
	(*RunResponse)(nil),     // 4: RunResponse
	(*emptypb.Empty)(nil),   // 5: google.protobuf.Empty
}
var file_proto_dockerpb_dockerpb_proto_depIdxs = []int32{
	5, // 0: DockerService.Version:input_type -> google.protobuf.Empty
	1, // 1: DockerService.Build:input_type -> BuildRequest
	3, // 2: DockerService.Run:input_type -> RunRequest
	0, // 3: DockerService.Version:output_type -> VersionResponse
	2, // 4: DockerService.Build:output_type -> BuildResponse
	4, // 5: DockerService.Run:output_type -> RunResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dockerpb_dockerpb_proto_init() }
func file_proto_dockerpb_dockerpb_proto_init() {
	if File_proto_dockerpb_dockerpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dockerpb_dockerpb_proto_rawDesc), len(file_proto_dockerpb_dockerpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dockerpb_dockerpb_proto_goTypes,
		DependencyIndexes: file_proto_dockerpb_dockerpb_proto_depIdxs,
		MessageInfos:      file_proto_dockerpb_dockerpb_proto_msgTypes,
	}.Build()
	File_proto_dockerpb_dockerpb_proto = out.File
	file_proto_dockerpb_dockerpb_proto_goTypes = nil
	file_proto_dockerpb_dockerpb_proto_depIdxs = nil
}
