// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/greeter/greeter.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HelloResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_greeter_greeter_proto protoreflect.FileDescriptor

const file_proto_greeter_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/greeter/greeter.proto\"\x1e\n" +
	"\bHelloReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\tHelloResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2,\n" +
	"\aGreeter\x12!\n" +
	"\bSayHello\x12\t.HelloReq\x1a\n" +
	".HelloRespBe\n" +
	"\x11com.daylily.protoB\x0fHelloworldProtoP\x01Z=github.com/Daylily-kor/daylily-docker-client/proto/helloworldb\x06proto3"

var (
	file_proto_greeter_greeter_proto_rawDescOnce sync.Once
	file_proto_greeter_greeter_proto_rawDescData []byte
)

func file_proto_greeter_greeter_proto_rawDescGZIP() []byte {
	file_proto_greeter_greeter_proto_rawDescOnce.Do(func() {
		file_proto_greeter_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeter_greeter_proto_rawDesc), len(file_proto_greeter_greeter_proto_rawDesc)))
	})
	return file_proto_greeter_greeter_proto_rawDescData
}

var file_proto_greeter_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_greeter_greeter_proto_goTypes = []any{
	(*HelloReq)(nil),  // 0: HelloReq
	(*HelloResp)(nil), // 1: HelloResp
}
var file_proto_greeter_greeter_proto_depIdxs = []int32{
	0, // 0: Greeter.SayHello:input_type -> HelloReq
	1, // 1: Greeter.SayHello:output_type -> HelloResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_greeter_greeter_proto_init() }
func file_proto_greeter_greeter_proto_init() {
	if File_proto_greeter_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeter_greeter_proto_rawDesc), len(file_proto_greeter_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greeter_greeter_proto_goTypes,
		DependencyIndexes: file_proto_greeter_greeter_proto_depIdxs,
		MessageInfos:      file_proto_greeter_greeter_proto_msgTypes,
	}.Build()
	File_proto_greeter_greeter_proto = out.File
	file_proto_greeter_greeter_proto_goTypes = nil
	file_proto_greeter_greeter_proto_depIdxs = nil
}
