// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: service.proto

package service

import (
	build "github.com/Daylily-kor/daylily-grpc-server/pb/build"
	run "github.com/Daylily-kor/daylily-grpc-server/pb/run"
	version "github.com/Daylily-kor/daylily-grpc-server/pb/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0ecom.daylily.pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\rversion.proto\x1a\vbuild.proto\x1a\trun.proto2\x9d\x02\n" +
	"\rDockerService\x12L\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a).com.daylily.pb.GrpcDockerVersionResponse\x12[\n" +
	"\n" +
	"ImageBuild\x12%.com.daylily.pb.GrpcImageBuildRequest\x1a&.com.daylily.pb.GrpcImageBuildResponse\x12a\n" +
	"\fContainerRun\x12'.com.daylily.pb.GrpcContainerRunRequest\x1a(.com.daylily.pb.GrpcContainerRunResponseBT\n" +
	"\x19com.daylily.proto.serviceP\x01Z5github.com/Daylily-kor/daylily-grpc-server/pb/serviceb\x06proto3"

var file_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                     // 0: google.protobuf.Empty
	(*build.GrpcImageBuildRequest)(nil),       // 1: com.daylily.pb.GrpcImageBuildRequest
	(*run.GrpcContainerRunRequest)(nil),       // 2: com.daylily.pb.GrpcContainerRunRequest
	(*version.GrpcDockerVersionResponse)(nil), // 3: com.daylily.pb.GrpcDockerVersionResponse
	(*build.GrpcImageBuildResponse)(nil),      // 4: com.daylily.pb.GrpcImageBuildResponse
	(*run.GrpcContainerRunResponse)(nil),      // 5: com.daylily.pb.GrpcContainerRunResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: com.daylily.pb.DockerService.Version:input_type -> google.protobuf.Empty
	1, // 1: com.daylily.pb.DockerService.ImageBuild:input_type -> com.daylily.pb.GrpcImageBuildRequest
	2, // 2: com.daylily.pb.DockerService.ContainerRun:input_type -> com.daylily.pb.GrpcContainerRunRequest
	3, // 3: com.daylily.pb.DockerService.Version:output_type -> com.daylily.pb.GrpcDockerVersionResponse
	4, // 4: com.daylily.pb.DockerService.ImageBuild:output_type -> com.daylily.pb.GrpcImageBuildResponse
	5, // 5: com.daylily.pb.DockerService.ContainerRun:output_type -> com.daylily.pb.GrpcContainerRunResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
