// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc1
// source: service.proto

package service

import (
	context "context"
	build "github.com/Daylily-kor/daylily-grpc-server/pb/build"
	containerList "github.com/Daylily-kor/daylily-grpc-server/pb/containerList"
	run "github.com/Daylily-kor/daylily-grpc-server/pb/run"
	version "github.com/Daylily-kor/daylily-grpc-server/pb/version"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerService_Version_FullMethodName       = "/com.daylily.pb.DockerService/Version"
	DockerService_ImageBuild_FullMethodName    = "/com.daylily.pb.DockerService/ImageBuild"
	DockerService_ContainerRun_FullMethodName  = "/com.daylily.pb.DockerService/ContainerRun"
	DockerService_ContainerList_FullMethodName = "/com.daylily.pb.DockerService/ContainerList"
)

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerServiceClient interface {
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*version.GrpcDockerVersionResponse, error)
	ImageBuild(ctx context.Context, in *build.GrpcImageBuildRequest, opts ...grpc.CallOption) (*build.GrpcImageBuildResponse, error)
	ContainerRun(ctx context.Context, in *run.GrpcContainerRunRequest, opts ...grpc.CallOption) (*run.GrpcContainerRunResponse, error)
	ContainerList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*containerList.GrpcContainerListResponse, error)
}

type dockerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerServiceClient(cc grpc.ClientConnInterface) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*version.GrpcDockerVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(version.GrpcDockerVersionResponse)
	err := c.cc.Invoke(ctx, DockerService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ImageBuild(ctx context.Context, in *build.GrpcImageBuildRequest, opts ...grpc.CallOption) (*build.GrpcImageBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(build.GrpcImageBuildResponse)
	err := c.cc.Invoke(ctx, DockerService_ImageBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerRun(ctx context.Context, in *run.GrpcContainerRunRequest, opts ...grpc.CallOption) (*run.GrpcContainerRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(run.GrpcContainerRunResponse)
	err := c.cc.Invoke(ctx, DockerService_ContainerRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*containerList.GrpcContainerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(containerList.GrpcContainerListResponse)
	err := c.cc.Invoke(ctx, DockerService_ContainerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerServiceServer is the server API for DockerService service.
// All implementations must embed UnimplementedDockerServiceServer
// for forward compatibility.
type DockerServiceServer interface {
	Version(context.Context, *emptypb.Empty) (*version.GrpcDockerVersionResponse, error)
	ImageBuild(context.Context, *build.GrpcImageBuildRequest) (*build.GrpcImageBuildResponse, error)
	ContainerRun(context.Context, *run.GrpcContainerRunRequest) (*run.GrpcContainerRunResponse, error)
	ContainerList(context.Context, *emptypb.Empty) (*containerList.GrpcContainerListResponse, error)
	mustEmbedUnimplementedDockerServiceServer()
}

// UnimplementedDockerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerServiceServer struct{}

func (UnimplementedDockerServiceServer) Version(context.Context, *emptypb.Empty) (*version.GrpcDockerVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedDockerServiceServer) ImageBuild(context.Context, *build.GrpcImageBuildRequest) (*build.GrpcImageBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageBuild not implemented")
}
func (UnimplementedDockerServiceServer) ContainerRun(context.Context, *run.GrpcContainerRunRequest) (*run.GrpcContainerRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRun not implemented")
}
func (UnimplementedDockerServiceServer) ContainerList(context.Context, *emptypb.Empty) (*containerList.GrpcContainerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerList not implemented")
}
func (UnimplementedDockerServiceServer) mustEmbedUnimplementedDockerServiceServer() {}
func (UnimplementedDockerServiceServer) testEmbeddedByValue()                       {}

// UnsafeDockerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerServiceServer will
// result in compilation errors.
type UnsafeDockerServiceServer interface {
	mustEmbedUnimplementedDockerServiceServer()
}

func RegisterDockerServiceServer(s grpc.ServiceRegistrar, srv DockerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDockerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerService_ServiceDesc, srv)
}

func _DockerService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ImageBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(build.GrpcImageBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageBuild(ctx, req.(*build.GrpcImageBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(run.GrpcContainerRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerRun(ctx, req.(*run.GrpcContainerRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerService_ServiceDesc is the grpc.ServiceDesc for DockerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.daylily.pb.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _DockerService_Version_Handler,
		},
		{
			MethodName: "ImageBuild",
			Handler:    _DockerService_ImageBuild_Handler,
		},
		{
			MethodName: "ContainerRun",
			Handler:    _DockerService_ContainerRun_Handler,
		},
		{
			MethodName: "ContainerList",
			Handler:    _DockerService_ContainerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
