// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: service.proto

package service

import (
	build "github.com/Daylily-kor/daylily-grpc-server/pb/build"
	run "github.com/Daylily-kor/daylily-grpc-server/pb/run"
	version "github.com/Daylily-kor/daylily-grpc-server/pb/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0ecom.daylily.pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\rversion.proto\x1a\vbuild.proto\x1a\trun.proto2\xe3\x01\n" +
	"\rDockerService\x12B\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\x1f.com.daylily.pb.VersionResponse\x12N\n" +
	"\x05Build\x12!.com.daylily.pb.ImageBuildRequest\x1a\".com.daylily.pb.ImageBuildResponse\x12>\n" +
	"\x03Run\x12\x1a.com.daylily.pb.RunRequest\x1a\x1b.com.daylily.pb.RunResponseBT\n" +
	"\x19com.daylily.proto.serviceP\x01Z5github.com/Daylily-kor/daylily-grpc-server/pb/serviceb\x06proto3"

var file_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),            // 0: google.protobuf.Empty
	(*build.ImageBuildRequest)(nil),  // 1: com.daylily.pb.ImageBuildRequest
	(*run.RunRequest)(nil),           // 2: com.daylily.pb.RunRequest
	(*version.VersionResponse)(nil),  // 3: com.daylily.pb.VersionResponse
	(*build.ImageBuildResponse)(nil), // 4: com.daylily.pb.ImageBuildResponse
	(*run.RunResponse)(nil),          // 5: com.daylily.pb.RunResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: com.daylily.pb.DockerService.Version:input_type -> google.protobuf.Empty
	1, // 1: com.daylily.pb.DockerService.Build:input_type -> com.daylily.pb.ImageBuildRequest
	2, // 2: com.daylily.pb.DockerService.Run:input_type -> com.daylily.pb.RunRequest
	3, // 3: com.daylily.pb.DockerService.Version:output_type -> com.daylily.pb.VersionResponse
	4, // 4: com.daylily.pb.DockerService.Build:output_type -> com.daylily.pb.ImageBuildResponse
	5, // 5: com.daylily.pb.DockerService.Run:output_type -> com.daylily.pb.RunResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
