// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: run.proto

package run

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcContainerRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcContainerRunRequest) Reset() {
	*x = GrpcContainerRunRequest{}
	mi := &file_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcContainerRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcContainerRunRequest) ProtoMessage() {}

func (x *GrpcContainerRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcContainerRunRequest.ProtoReflect.Descriptor instead.
func (*GrpcContainerRunRequest) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcContainerRunRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *GrpcContainerRunRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type GrpcContainerRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcContainerRunResponse) Reset() {
	*x = GrpcContainerRunResponse{}
	mi := &file_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcContainerRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcContainerRunResponse) ProtoMessage() {}

func (x *GrpcContainerRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcContainerRunResponse.ProtoReflect.Descriptor instead.
func (*GrpcContainerRunResponse) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcContainerRunResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GrpcContainerRunResponse) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GrpcContainerRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_run_proto protoreflect.FileDescriptor

const file_run_proto_rawDesc = "" +
	"\n" +
	"\trun.proto\x12\x0ecom.daylily.pb\"[\n" +
	"\x17GrpcContainerRunRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\"|\n" +
	"\x18GrpcContainerRunResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusBL\n" +
	"\x15com.daylily.proto.runP\x01Z1github.com/Daylily-kor/daylily-grpc-server/pb/runb\x06proto3"

var (
	file_run_proto_rawDescOnce sync.Once
	file_run_proto_rawDescData []byte
)

func file_run_proto_rawDescGZIP() []byte {
	file_run_proto_rawDescOnce.Do(func() {
		file_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_run_proto_rawDesc), len(file_run_proto_rawDesc)))
	})
	return file_run_proto_rawDescData
}

var file_run_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_run_proto_goTypes = []any{
	(*GrpcContainerRunRequest)(nil),  // 0: com.daylily.pb.GrpcContainerRunRequest
	(*GrpcContainerRunResponse)(nil), // 1: com.daylily.pb.GrpcContainerRunResponse
}
var file_run_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_run_proto_init() }
func file_run_proto_init() {
	if File_run_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_run_proto_rawDesc), len(file_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_run_proto_goTypes,
		DependencyIndexes: file_run_proto_depIdxs,
		MessageInfos:      file_run_proto_msgTypes,
	}.Build()
	File_run_proto = out.File
	file_run_proto_goTypes = nil
	file_run_proto_depIdxs = nil
}
