// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: containerList.proto

package containerList

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcContainerResponse) Reset() {
	*x = GrpcContainerResponse{}
	mi := &file_containerList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcContainerResponse) ProtoMessage() {}

func (x *GrpcContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcContainerResponse.ProtoReflect.Descriptor instead.
func (*GrpcContainerResponse) Descriptor() ([]byte, []int) {
	return file_containerList_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GrpcContainerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcContainerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GrpcContainerResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GrpcContainerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GrpcContainerListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Containers    []*GrpcContainerResponse `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcContainerListResponse) Reset() {
	*x = GrpcContainerListResponse{}
	mi := &file_containerList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcContainerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcContainerListResponse) ProtoMessage() {}

func (x *GrpcContainerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcContainerListResponse.ProtoReflect.Descriptor instead.
func (*GrpcContainerListResponse) Descriptor() ([]byte, []int) {
	return file_containerList_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcContainerListResponse) GetContainers() []*GrpcContainerResponse {
	if x != nil {
		return x.Containers
	}
	return nil
}

var File_containerList_proto protoreflect.FileDescriptor

const file_containerList_proto_rawDesc = "" +
	"\n" +
	"\x13containerList.proto\x12\x0ecom.daylily.pb\"{\n" +
	"\x15GrpcContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"b\n" +
	"\x19GrpcContainerListResponse\x12E\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2%.com.daylily.pb.GrpcContainerResponseR\n" +
	"containersB`\n" +
	"\x1fcom.daylily.proto.containerListP\x01Z;github.com/Daylily-kor/daylily-grpc-server/pb/containerListb\x06proto3"

var (
	file_containerList_proto_rawDescOnce sync.Once
	file_containerList_proto_rawDescData []byte
)

func file_containerList_proto_rawDescGZIP() []byte {
	file_containerList_proto_rawDescOnce.Do(func() {
		file_containerList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containerList_proto_rawDesc), len(file_containerList_proto_rawDesc)))
	})
	return file_containerList_proto_rawDescData
}

var file_containerList_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_containerList_proto_goTypes = []any{
	(*GrpcContainerResponse)(nil),     // 0: com.daylily.pb.GrpcContainerResponse
	(*GrpcContainerListResponse)(nil), // 1: com.daylily.pb.GrpcContainerListResponse
}
var file_containerList_proto_depIdxs = []int32{
	0, // 0: com.daylily.pb.GrpcContainerListResponse.containers:type_name -> com.daylily.pb.GrpcContainerResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_containerList_proto_init() }
func file_containerList_proto_init() {
	if File_containerList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containerList_proto_rawDesc), len(file_containerList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_containerList_proto_goTypes,
		DependencyIndexes: file_containerList_proto_depIdxs,
		MessageInfos:      file_containerList_proto_msgTypes,
	}.Build()
	File_containerList_proto = out.File
	file_containerList_proto_goTypes = nil
	file_containerList_proto_depIdxs = nil
}
